### ISSUE TITLE
Documentation: Suggest adding docker to sudoers

### ISSUE THREAD

**Issue by futurepaul** [vulpemventures/nigiri#101]
Hey, I had a couple of problems with installing this on Linux (using PopOS, which is basically Ubuntu):

1. Putting a `bin` folder in my home folder feels a little rude and requires me to edit my .bash_profile. If this is standard practice it's news to me.
2. There seem to be hardcoded expectations in nigiri to run with a non-sudo docker. I needed to follow these instructions https://docs.docker.com/engine/install/linux-postinstall/ before I could get nigiri to run successfully. Before I did that,`nigiri start` couldn't find docker, and `sudo nigiri start` was looking for the config in `/root/...`.

**Comment by tiero** [comment]
Hello @futurepaul. Thanks for reaching out.

I personally use PopOS too, and I didn't had to modify my bash profile. Anyhow, we didn't thought much about the position of the binary. Since the data directory is created by the binary itself, we should have a place outside it. I agree that may stay in:

- `usr/local/bin`
- `/usr/bin` 
or something else, please suggest.

About docker, yes, we expect to be w/o sudo, because Well, so as not to use sudo frequently in development, it would be useful to let users be members of docker. Curious to see if in development when you run a docker container you prefer to type everytime sudo? Seems slowing down development lifecycle...Nigiri is development regtest box after all, no supposed to be run on linux server.

**Comment by futurepaul** [comment]
I believe that `/usr/local/bin` is appropriate here: https://unix.stackexchange.com/questions/8656/usr-bin-vs-usr-local-bin-on-linux

I don't prefer to use with or without sudo I don't actually use docker on this machine usually. I just didn't understand why nigiri wasn't working and it turns out it requires non-sudo, which isn't the default out-of-the-box experience of docker. I think a note in the install instructions would be plenty to clear it up.

**Comment by tiero** [comment]
Sure, will do. Editing the title, so will close this once we improve the documentation. Will create additional issue in nigiri-installer-script for changing the directory of the binary.

Thanks
